-- ================================================================
-- DJ INGRID SPOTIFY STATS
-- BASE DE DATOS + VISTAS PÚBLICAS DEL DASHBOARD
-- ================================================================

-- 1. TABLA PRINCIPAL
CREATE TABLE IF NOT EXISTS public.spotify_history_extended (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    played_at TIMESTAMPTZ NOT NULL,
    track_name TEXT NOT NULL,
    artist_name TEXT NOT NULL,
    album_name TEXT,
    album_cover TEXT,
    spotify_track_uri TEXT,
    spotify_album_uri TEXT,
    ms_played BIGINT NOT NULL DEFAULT 0,
    skipped BOOLEAN NOT NULL DEFAULT FALSE,
    shuffle BOOLEAN NOT NULL DEFAULT FALSE,
    offline BOOLEAN NOT NULL DEFAULT FALSE,
    incognito_mode BOOLEAN NOT NULL DEFAULT FALSE,
    source_file TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Compatibilidad con tablas creadas anteriormente.
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS source_key TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS played_at TIMESTAMPTZ;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS track_name TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS artist_name TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS album_name TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS album_cover TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS spotify_track_uri TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS spotify_album_uri TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS ms_played BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS skipped BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS shuffle BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS offline BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS incognito_mode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS source_file TEXT;
ALTER TABLE public.spotify_history_extended ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ================================================================
-- CORRECCIÓN CRÍTICA:
-- El proyecto NO usa played_at + track + artist como deduplicación.
-- La única clave de deduplicación oficial es source_key.
-- ================================================================

ALTER TABLE public.spotify_history_extended
DROP CONSTRAINT IF EXISTS unique_played_at_track;

DROP INDEX IF EXISTS public.unique_played_at_track;

CREATE UNIQUE INDEX IF NOT EXISTS uq_spotify_history_extended_source_key
    ON public.spotify_history_extended (source_key);

-- 2. ÍNDICES
CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_played_at
    ON public.spotify_history_extended (played_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_track_artist
    ON public.spotify_history_extended (track_name, artist_name);

CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_track_uri
    ON public.spotify_history_extended (spotify_track_uri);

-- 3. RLS Y PERMISOS
ALTER TABLE public.spotify_history_extended ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read spotify history" ON public.spotify_history_extended;

REVOKE ALL ON TABLE public.spotify_history_extended FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- 4. ESTADÍSTICAS GENERALES
CREATE OR REPLACE VIEW public.view_stats_general
WITH (security_invoker = false)
AS
SELECT
    COUNT(*)::INT AS total_plays,
    COUNT(DISTINCT LOWER(BTRIM(artist_name)))::INT AS total_artistas
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> '';

-- 5. TOP 10 CANCIONES - ÚLTIMOS 90 DÍAS
CREATE OR REPLACE VIEW public.view_top_tracks_recent
WITH (security_invoker = false)
AS
SELECT
    track_name,
    artist_name,
    MAX(album_name) AS album_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_track_uri) FILTER (
        WHERE spotify_track_uri IS NOT NULL AND BTRIM(spotify_track_uri) <> ''
    ) AS spotify_track_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE played_at >= CURRENT_TIMESTAMP - INTERVAL '90 days'
  AND ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(artist_name) <> ''
GROUP BY track_name, artist_name
ORDER BY veces_reproducidas DESC, track_name ASC, artist_name ASC
LIMIT 10;

-- 6. TOP 5 ÁLBUMES - ÚLTIMOS 90 DÍAS
CREATE OR REPLACE VIEW public.view_top_albums_recent
WITH (security_invoker = false)
AS
SELECT
    BTRIM(album_name) AS album_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_album_uri) FILTER (
        WHERE spotify_album_uri IS NOT NULL AND BTRIM(spotify_album_uri) <> ''
    ) AS spotify_album_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE played_at >= CURRENT_TIMESTAMP - INTERVAL '90 days'
  AND ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(artist_name) <> ''
  AND BTRIM(COALESCE(album_name, '')) <> ''
GROUP BY BTRIM(album_name), artist_name
ORDER BY veces_reproducidas DESC, album_name ASC, artist_name ASC
LIMIT 5;

-- 7. TOP 10 CANCIONES - TODOS LOS TIEMPOS
CREATE OR REPLACE VIEW public.view_top_tracks_all_time
WITH (security_invoker = false)
AS
SELECT
    track_name,
    artist_name,
    MAX(album_name) AS album_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_track_uri) FILTER (
        WHERE spotify_track_uri IS NOT NULL AND BTRIM(spotify_track_uri) <> ''
    ) AS spotify_track_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(artist_name) <> ''
GROUP BY track_name, artist_name
HAVING COUNT(*) >= 50
ORDER BY veces_reproducidas DESC, track_name ASC, artist_name ASC
LIMIT 10;

-- 8. TOP 5 ÁLBUMES - TODOS LOS TIEMPOS
CREATE OR REPLACE VIEW public.view_top_albums_all_time
WITH (security_invoker = false)
AS
SELECT
    BTRIM(album_name) AS album_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_album_uri) FILTER (
        WHERE spotify_album_uri IS NOT NULL AND BTRIM(spotify_album_uri) <> ''
    ) AS spotify_album_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(artist_name) <> ''
  AND BTRIM(COALESCE(album_name, '')) <> ''
GROUP BY BTRIM(album_name), artist_name
ORDER BY veces_reproducidas DESC, album_name ASC, artist_name ASC
LIMIT 5;

-- 9. ÚLTIMAS 20 REPRODUCCIONES
CREATE OR REPLACE VIEW public.view_recent_plays
WITH (security_invoker = false)
AS
SELECT
    id,
    track_name,
    artist_name,
    album_name,
    album_cover,
    spotify_track_uri,
    played_at,
    ms_played
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(artist_name) <> ''
ORDER BY played_at DESC, id DESC
LIMIT 20;

-- 10. SOLO LAS VISTAS NECESARIAS SON PÚBLICAS
GRANT SELECT ON public.view_stats_general TO anon, authenticated;
GRANT SELECT ON public.view_top_tracks_recent TO anon, authenticated;
GRANT SELECT ON public.view_top_albums_recent TO anon, authenticated;
GRANT SELECT ON public.view_top_tracks_all_time TO anon, authenticated;
GRANT SELECT ON public.view_top_albums_all_time TO anon, authenticated;
GRANT SELECT ON public.view_recent_plays TO anon, authenticated;

-- 11. COMPROBACIONES
SELECT
    'spotify_history_extended' AS objeto,
    COUNT(*) AS registros
FROM public.spotify_history_extended
UNION ALL
SELECT 'view_stats_general', COUNT(*) FROM public.view_stats_general
UNION ALL
SELECT 'view_top_tracks_recent', COUNT(*) FROM public.view_top_tracks_recent
UNION ALL
SELECT 'view_top_albums_recent', COUNT(*) FROM public.view_top_albums_recent
UNION ALL
SELECT 'view_top_tracks_all_time', COUNT(*) FROM public.view_top_tracks_all_time
UNION ALL
SELECT 'view_top_albums_all_time', COUNT(*) FROM public.view_top_albums_all_time
UNION ALL
SELECT 'view_recent_plays', COUNT(*) FROM public.view_recent_plays;

-- 12. COMPROBAR QUE LA RESTRICCIÓN ANTIGUA NO QUEDÓ
SELECT
    indexname
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename = 'spotify_history_extended'
  AND indexname = 'unique_played_at_track';
